### ISSUE TITLE
Report URL shows 'undefined' before selecting a website

### ISSUE THREAD

**Issue by bensulli** [siteinspector/siteinspector#10]
Very minor, but the URL for the report shows as 'undefined' until you select a website to make the report for. It should probably just be blank until you've selected a website.

https://inspector.skyraker.caundefined

![image](https://user-images.githubusercontent.com/6107886/111041139-a395f880-83eb-11eb-9965-fc02da017796.png)

**Comment by omohokcoj** [comment]
@bensulli it has been fixed in the latest docker image 😃

**Comment by bensulli** [comment]
Confirmed fixed! Wow, quick fix :)
