### ISSUE TITLE
mimemagic no longer supported

### ISSUE THREAD

**Issue by devhops** [siteinspector/siteinspector#12]
I am trying to run this in GCP (Run) and I get the following error on the build step using the Dockerfile

Step #0 - "Build": Fetching gem metadata from https://rubygems.org/.........
Step #0 - "Build": Your bundle is locked to mimemagic (0.3.5), but that version could not be found
Step #0 - "Build": in any of the sources listed in your Gemfile. If you haven't changed sources,
Step #0 - "Build": that means the author of mimemagic (0.3.5) has removed it. You'll need to update
Step #0 - "Build": your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
Step #0 - "Build": in order to install.
Step #0 - "Build": The command '/bin/sh -c bundle config set with 'production' && bundle install && gem install foreman' returned a non-zero code: 7
Finished Step #0 - "Build"

**Comment by omohokcoj** [comment]
@devhops unfortunately it's impossible to run SiteInspector on the Google Cloud Run platform because it does not support background jobs. SiteInspector uses Sidekiq background jobs to crawl and process website pages asynchronously.
Alternatively you can try Google App Engine or Kubernetes Engine.

**Comment by devhops** [comment]
> @devhops unfortunately it's impossible to run SiteInspector on the Google Cloud Run platform because it does not support background jobs. SiteInspector uses Sidekiq background jobs to crawl and process website pages asynchronously.
> Alternatively you can try Google App Engine or Kubernetes Engine.

Thank you, would it work in Heroku still? I encountered the same message trying to deploy the app there. If not, I will look for something else, I wanted a free hosting solution so I could try it out.

**Comment by omohokcoj** [comment]
@devhops heroku build should work in the latest master.
You can use this link to deploy to heroku - https://heroku.com/deploy?template=https://github.com/siteinspector/siteinspector
Make sure that heroku worker dyno is turned on once the app is deployed (`heroku ps:scale worker=1 -a <app-name>`)
