### ISSUE TITLE
Unable to save 'check images' setting

### ISSUE THREAD

**Issue by mahood73** [siteinspector/siteinspector#22]
Hi there,
I've just installed a self-hosted version of Site Inspector which is working well, except for one issue.

When I add a new site or update an existing one, it always sets 'Check images' and 'Check scripts' to OFF.

Is there any way to get this setting to stick? No error shows up in the logs, and I cannot find any additional documentation on your website.

Thanks!

**Comment by omohokcoj** [comment]
@mahood73 thanks for reporting this bug - it has been fixed in the newest docker image:
https://hub.docker.com/layers/siteinspector/siteinspector/1.0.5/images/sha256-91ec4945ad67e0e4b93c37db5693c3493899ee19eccb4b3f866664da97a4ea45?context=repo

**Comment by mahood73** [comment]
Thank you for the quick reply!
I've pulled the latest image and can confirm it's working for me as expected.
