### ISSUE TITLE
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with bin/rails credentials:edit

### ISSUE THREAD

**Issue by tjhackzy** [siteinspector/siteinspector#24]
While deploying it with portainer, I am getting : 
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with bin/rails credentials:edit. 

Full log:

rake aborted!,
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit`,
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/application.rb:596:in `validate_secret_key_base',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/application.rb:430:in `secret_key_base',
/usr/local/bundle/gems/devise-4.7.3/lib/devise/secret_key_finder.rb:24:in `key_exists?',
/usr/local/bundle/gems/devise-4.7.3/lib/devise/secret_key_finder.rb:16:in `find',
/usr/local/bundle/gems/devise-4.7.3/lib/devise/rails.rb:37:in `block in <class:Engine>',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `instance_exec',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `run',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/initializable.rb:61:in `block in run_initializers',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/initializable.rb:60:in `run_initializers',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/application.rb:384:in `initialize!',
/opt/siteinspector/config/environment.rb:7:in `<main>',
/usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require',
/usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi',
/usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register',
/usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi',
/usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require',
/usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require',
/usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `block in require',
/usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency',
/usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/application.rb:360:in `require_environment!',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/application.rb:526:in `block in run_tasks_blocks',
Tasks: TOP => db:migrate => db:load_config => environment,
(See full trace by running task with --trace),
rake aborted!,
ArgumentError: Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit`,
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/application.rb:596:in `validate_secret_key_base',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/application.rb:430:in `secret_key_base',
/usr/local/bundle/gems/devise-4.7.3/lib/devise/secret_key_finder.rb:24:in `key_exists?',
/usr/local/bundle/gems/devise-4.7.3/lib/devise/secret_key_finder.rb:16:in `find',
/usr/local/bundle/gems/devise-4.7.3/lib/devise/rails.rb:37:in `block in <class:Engine>',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `instance_exec',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/initializable.rb:32:in `run',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/initializable.rb:61:in `block in run_initializers',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/initializable.rb:60:in `run_initializers',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/application.rb:384:in `initialize!',
/opt/siteinspector/config/environment.rb:7:in `<main>',
/usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require',
/usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi',
/usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register',
/usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi',
/usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require',
/usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require',
/usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `block in require',
/usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:299:in `load_dependency',
/usr/local/bundle/gems/activesupport-6.1.3.1/lib/active_support/dependencies.rb:332:in `require',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/application.rb:360:in `require_environment!',
/usr/local/bundle/gems/railties-6.1.3.1/lib/rails/application.rb:526:in `block in run_tasks_blocks',
Tasks: TOP => db:migrate => db:load_config => environment,
(See full trace by running task with --trace)

Can anyone help me with this?

**Comment by tjhackzy** [comment]
Never mind. I forgot to add openssl rand -hex 64

**Comment by timwsuqld** [comment]
For anyone else hitting this, run `sed -i "s/SECRET_KEY_BASE:/SECRET_KEY_BASE: `openssl rand -hex 64`/" docker-compose.yml` after downloading the docker-compose file. This really should be part of the README
