### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by haltonbc** [siteinspector/siteinspector#26]
Hello - when deploying to Heroku I get the following error:
<img width="531" alt="error" src="https://user-images.githubusercontent.com/29772464/154458315-f29c7a24-e7af-48e3-99e7-cdd55c95f300.png">
 Apologies if this is the wrong place to post this

**Comment by omohokcoj** [comment]
@haltonbc it has been fixed - you can try to deploy now
