### ISSUE TITLE
Segmentation fault exited with code 139

### ISSUE THREAD

**Issue by memv** [siteinspector/siteinspector#31]
I am hitting this issue with the box stopping after starting the docker app container. I have a macbook pro M1 Max with 64GB RAM, with 32GB available to docker in the settings inside of preferences. I tried combinations of 6 or 10 CPUs and tried a few different settings for SIDEKIQ_CONCURRENCY in the yml file between 4-16 but not getting anywhere with it unfortunately.

```
15:09:21 worker.1 | Segmentation fault
15:09:21 worker.1 | exited with code 139
15:09:21 system   | sending SIGTERM to all processes
15:09:21 web.1    | - Gracefully stopping, waiting for requests to finish
15:09:21 web.1    | terminated by SIGTERM
```

**Comment by jamesanderson9182** [comment]
I also got this error on my M1 Mac mini

**Comment by omohokcoj** [comment]
@jamesanderson9182 @memv the app has been updated to ruby 3.1.0 - most likely it should fix the issue on m1 (though i didn't experience it on my m1 air with the old version)

**Comment by jamesanderson9182** [comment]
Thank you. I’ll give it a try next time I’m on that machine. Was experimenting on my own machine before deploying it into a home server. Really useful and easy to use!
