### ISSUE TITLE
Decrease SiteInspector security risk exposure

### ISSUE THREAD

**Issue by mulder999** [siteinspector/siteinspector#36]
SiteInspector is a great tool but it's container has a huge number of vulnerabilities:
- 14 critical
- 50 high
- 87 medium
- 3 low

Most of them come from Git and ImageMagick which should likely not even be packaged in the container in the first place.

![SiteInspectorVulnerabilites](https://user-images.githubusercontent.com/1905023/199728404-cd316be4-b7bc-48f5-a690-56d78507a39e.JPG)

Details of vulnerabilities through [Vulnerability exposure file](https://github.com/siteinspector/siteinspector/files/9929351/5504d159-f970-4a4a-9bb0-fb59f2553ecb-vex.cdx.json.zip)

This file type can be imported in [OWASP Dependency-Track](https://dependencytrack.org/) or its [online SaaS](https://yoursky.blue/dependency-track-saas/) variant

**Comment by omohokcoj** [comment]
@mulder999 it doesn't seem like those 'vulnerabilities' are legit.
