### ISSUE TITLE
Recover/reset forgotten password

### ISSUE THREAD

**Issue by gemesa** [siteinspector/siteinspector#38]
Is there any way to reset/recover my forgotten password? I did not find any so far.

**Comment by omohokcoj** [comment]
@gemesa unfortunately there are no easy ways - but you can try to run `docker stats` to find your siteinspector server container name  and then execute:
`docker exec -it rails c <container-name>`
and now from the rails console you can update the password: `User.find_by(email: 'your-email').update(password: 'new-passord')`
