### ISSUE TITLE
Request: Ability to change the site's root URL/domain

### ISSUE THREAD

**Issue by bensulli** [siteinspector/siteinspector#8]
Hi,

I've deployed SiteInspector and loving the features so far! I'm using it behind an nginx reverse proxy to handle SSL to the local http://0.0.0.0:808 install. However, this means my 'share' report URLs are incorrect. Is there a way to tell SiteInspector to use https://inspector.mydomain.com as the root domain?

Thanks!

**Comment by omohokcoj** [comment]
@bensulli this might be related to reverse proxy configs (proxy should send forwarded host header to make it generate the correct URLs on the back end).

Anyways, there is an easy way to fix this by using the original host URL from the browser location.
This fix has been added to the new 1.0.4 release (you might need to set this version in your docker-compose file)

**Comment by bensulli** [comment]
Confirmed fixed with the proxy config and 1.0.4!
