### ISSUE TITLE
Direct link to a PDF is marked as a broken link

### ISSUE THREAD

**Issue by bensulli** [siteinspector/siteinspector#9]
Scanning https://appliedmammal.com marks three PDF links as broken, but they appear to be just fine.

An example:
https://appliedmammal.com/content/brochures/Forest%20Herbicide%20Use.pdf

**Comment by omohokcoj** [comment]
@bensulli this issue was caused by whitespaces in the URLs - it has been fixed in 1.0.4

**Comment by bensulli** [comment]
Confirmed fixed :)
